### ISSUE TITLE
Add possibility to everyone to create a conference

### ISSUE THREAD

**Issue by juliensl** [wreiske/Rocket.Chat.App-WebEx#7]
Hi ! 

I am not sur if it is possible or not, but it could be very nice if everybody in your rocket chat server has the possibility to create a video conference, using the /webex command.

Currently, when I am trying create a webinar using /webex, I am going to a page with the error : 
"We cannot find the personal room of ... Please try again"

I think it is because I am not connected.

When I try connected, It is saying that I should check the ID :disappointed: 

Could you explain me how it works exactly please ? Do I have the possibility to use this service like a jitsi meet ? :smiley: 

Thank you for your work !

**Comment by coach1988** [comment]
Hi Julien,

I've tried this app today for the first time, too, and i got it working by using "/webex myusername". This will create a personal meeting room if the user account has the permission to create such 'ad-hoc' meetings.
I initially had some trouble because i was logged in with our admin account and the user that should start the meetings was a different one. after logging out and logging in (in the browser) with the correct username, it worked.

PS: Yep, thanks for this work, we're currently evaluating Rocket.Chat as an alternative to SLACK/MS Teams and it's doing great so far.

**Comment by wreiske** [comment]
I think the issue @juliensl is having is different. WebEx is not a free service, so you'll have to make sure your company is signed up to use WebEx and has a valid company URL (company.webex.com, for example.) When you configure the WebEx app, type in the company name in the settings and it should work. 

I'm assuming based on the error you were seeing is that you either did not configure the company setting correctly, or you do not pay to use WebEx.

**Comment by juliensl** [comment]
Hi everybody.

Finally, I cannot use the addon for my project, because you right @wreiske , If I want to use WebEx like I want, I should add all people in my professional account.

We can close this issue I think :) 

Thank you, and have a good day !
